#! /bin/bash
docker-compose start postgres redis &&
docker exec -it getout-postgres-1 bash -c "PGPASSWORD=docker psql -h postgres -U postgres -d getout-db -c \"DELETE FROM account WHERE email LIKE '%@test.com';\"" &&
npm test