###
POST http://localhost:8080/account/oauth HTTP/1.1
Content-Type: application/json

{
    "email": "perry@oauth.com",
    "idToken": "tokenDeFou"
}

###
GET http://localhost:8080/session HTTP/1.1
Content-Type: application/json

###
POST http://localhost:8080/account/signup HTTP/1.1
Content-Type: application/json

{
    "email": "yo2@yo.com",
    "password": "123456",
    "firstName": "Julien",
    "lastName": "Letoux",
    "bornDate": "07/06/2001",
    "salt": "sdjqshjodijaoz"
}

###
GET http://localhost:8080/session HTTP/1.1
Content-Type: application/json

###
POST http://localhost:8080/account/login HTTP/1.1
Content-Type: application/json

{
    "email": "yo2@yo.com",
    "password": "123456"
}

###
GET http://localhost:8080/session HTTP/1.1
Content-Type: application/json

###
POST http://localhost:8080/account/logout HTTP/1.1
Content-Type: application/json

{
    "email": "yo@yo.com",
    "password": "123456"
}

###
POST http://localhost:8080/account/reset-password HTTP/1.1
Content-Type: application/json

{
    "password": "123456",
    "newPassword": "123457"
}
