name: Back Lint and Build

on:
  push:
    branches:
      - dev

defaults:
  run:
    working-directory: ./backend
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
        - name : Checkout
          uses: actions/checkout@v3.5.3

        - name: Run Linter
          run: npx eslint --ext .ts ./src

        - name: Build
          run: npm run build