name: Backend deployment

on:
  push:
    branches:
      - prod

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
        - name: Checkout
          uses: actions/checkout@v2

        - name: SSH and deploy
          uses: appleboy/ssh-action@master
          with:
            host: ${{ secrets.SSH_HOST }}
            username: admin-getout
            key: ${{ secrets.SSH_KEY }}
            script: "sudo /root/pull_and_redeploy_backend.sh"
