name: Flutter Build and Release

on:
  push:
    tags:
      - v*

defaults:
  run:
    working-directory: ./app
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name : Checkout
        uses: actions/checkout@v3.5.3

      - uses: actions/setup-java@v3.11.0
        with:
          distribution: 'microsoft'
          java-version: "17"

      - uses: subosito/flutter-action@v2.10.0
        with:
          flutter-version: '3.10.4'
          channel: 'stable'
          cache: true

      - name: Build APK
        run: flutter build apk

      - name: Upload APK to Releases
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: app/build/app/outputs/flutter-apk/app-release.apk