name: Flutter Build and Release

on:
  push:
    tags:
      - v*

defaults:
  run:
    working-directory: ./app
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name : Checkout
        uses: actions/checkout@v3.5.3

      - uses: actions/setup-java@v3.11.0
        with:
          distribution: 'microsoft'
          java-version: "17"

      - uses: subosito/flutter-action@v2.10.0
        with:
          flutter-version: '3.10.4'
          channel: 'stable'
          cache: true

      - name: Build APK
        run: flutter build apk

      - name: ls
        run: ls -la build/app/outputs/flutter-apk/

      - name: Artifact Upload
        uses: actions/upload-artifact@v2
        with:
          name: app-release.apk
          path: build/app/outputs/flutter-apk/app-release.apk

      - name: Upload APK to Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: "app-release.apk"
