name: Flutter Build and Release

on:
  push:
    tags:
      - v*

defaults:
  run:
#    working-directory: ./app
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name : Checkout
        uses: actions/checkout@v3.5.3

      #- uses: actions/setup-java@v3.11.0
      #  with:
      #    distribution: 'microsoft'
      #    java-version: "17"
#
      #- uses: subosito/flutter-action@v2.10.0
      #  with:
      #    flutter-version: '3.10.4'
      #    channel: 'stable'
      #    cache: true
#
      #- name: Build APK
      #  run: flutter build apk


      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
      
      - name: Upload APK to Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: "./README.md"
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref }}