name: Flutter CI

on:
  push:
    branches:
      - dev
    # paths:
    #   - app/**

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     defaults:
#       run:
#         working-directory: app
#     steps:
#       - uses: actions/checkout@v1
#       - uses: actions/setup-java@v1
#         with:
#           java-version: '12.x'
#       - uses: subosito/flutter-action@v1
#         with:
#           channel: 'beta'
#       - run: flutter pub get
#       - run: dart format --set-exit-if-changed .
#       - run: flutter analyze .
#       - run: flutter build apk
#       - uses: actions/upload-artifact@v1
#         with:
#           name: release-apk
#           path: build/app/outputs/apk/release/app-release.apk

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: app
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'microsoft'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.0.0"
          channel: 'stable'
      - name: Get dependencies
        run: flutter pub get

      # Runs a set of commands using the runners shell
      - name: Start release build
        run: flutter build appbundle