name: Frontend linter

on:
  push:
    branches:
      - dev
      - app/upgrade_dependencies
    paths:
      - 'app/**'

defaults:
  run:
    shell: bash

jobs:
  Frontend-linter:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name : Checkout
        uses: actions/checkout@v4.1.1

      - name: Set up Java
        uses: actions/setup-java@v4.0.0
        with:
          distribution: 'microsoft'
          java-version: "17"

      - name: Set up Flutter
        uses: subosito/flutter-action@v2.12.0
        with:
          flutter-version: '3.16.0'
          channel: 'stable'
          cache: true

      - name: Lint App
        run: |
          cd app/
          flutter pub get
          flutter analyze