name: Frontend linter

on:
  push:
    branches:
      - dev
      - app
    paths:
      - 'app/**'

defaults:
  run:
    working-directory: ./app
    shell: bash

jobs:
  Frontend-linter:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name : Checkout
        uses: actions/checkout@v4.2.1

      - name: Set up Java 17 Microsoft
        uses: actions/setup-java@v4.4.0
        with:
          distribution: 'microsoft'
          java-version: '17'

      - name: Set up Flutter 3.24.3
        uses: subosito/flutter-action@v2.16.0
        with:
          flutter-version: '3.24.3'
          channel: 'stable'
          cache: true

      - name: Get dependencies
        run: flutter pub get

      - name: Lint App
        run: flutter analyze