name: Frontend deployment

on:
  workflow_dispatch: # This event allows you to manually trigger the workflow

defaults:
  run:
    working-directory: ./app
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name : Checkout
        uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0

      - uses: actions/setup-java@v4.0.0
        with:
          distribution: 'microsoft'
          java-version: "17"

      - uses: subosito/flutter-action@v2.12.0
        with:
          flutter-version: '3.16.0'
          channel: 'stable'
          cache: true

      - name: Get dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release

      - name: 'Get Previous tag'
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@v1.3.0"

      - name: create release
        uses: softprops/action-gh-release@v0.1.15
        with:
          files: |
            ./app/build/app/outputs/flutter-apk/app-release.apk
          tag_name: ${{ steps.previoustag.outputs.tag }}
          token: ${{ secrets.RELEASE_GA_TOKEN }}