name: Frontend unit tests

on:
  push:
    branches:
      - '*'
    paths-ignore:
      - 'prod/**'

defaults:
  run:
    working-directory: ./app
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name : Checkout
        uses: actions/checkout@v4.1.1

      - name: Set up Java
        uses: actions/setup-java@v4.0.0
        with:
          distribution: 'microsoft'
          java-version: "17"

      - name: Set up Flutter
        uses: subosito/flutter-action@v2.12.0
        with:
          flutter-version: '3.16.0'
          channel: 'stable'
          cache: true

      - name: Run Flutter tests
        run: flutter test