name: Frontend deployment

on:
  workflow_dispatch: # This event allows you to manually trigger the workflow

defaults:
  run:
    working-directory: ./app
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name : Checkout
        uses: actions/checkout@v3.5.3
        with:
          fetch-depth: 0

      - uses: actions/setup-java@v3.11.0
        with:
          distribution: 'microsoft'
          java-version: "17"

      - uses: subosito/flutter-action@v2.10.0
        with:
          flutter-version: '3.10.4'
          channel: 'stable'
          cache: true

      - name: Build APK
        run: flutter build apk

      - name: 'Get Previous tag'
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
      
      - name: create release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ./app/build/app/outputs/flutter-apk/app-release.apk
          tag_name: ${{ steps.previoustag.outputs.tag }}
          token: ${{ secrets.RELEASE_GA_TOKEN }}