name: Frontend unit tests

on:
  push:
    branches:
      - '*'
    paths-ignore:
      - 'prod/**'

defaults:
  run:
    working-directory: ./app
    shell: bash

jobs:
  Frontend-unit-tests:
    runs-on: ubuntu-latest

    steps:
      - name : Checkout
        uses: actions/checkout@v4.1.7

      - name: Set up Java 17 Microsoft
        uses: actions/setup-java@v4.2.2
        with:
          distribution: 'microsoft'
          java-version: '17'

      - name: Set up Flutter 3.24.2
        uses: subosito/flutter-action@v2.16.0
        with:
          flutter-version: '3.24.2'
          channel: 'stable'
          cache: true

      - name: Get dependencies
        run: flutter pub get

      - name: Run Flutter tests
        run: flutter test