name: Frontend linter

on:
  push:
    branches:
      - dev
      - app
    paths:
      - 'app/**'

defaults:
  run:
    working-directory: ./app
    shell: bash

jobs:
  Frontend-linter:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name : Checkout
        uses: actions/checkout@v4.1.1

      - name: Set up Java 17 Microsoft
        uses: actions/setup-java@v4.0.0
        with:
          distribution: 'microsoft'
          java-version: '17'

      - name: Set up Flutter 3.19.0
        uses: subosito/flutter-action@v2.12.0
        with:
          flutter-version: '3.19.0'
          channel: 'stable'
          cache: true

      - name: Get dependencies
        run: flutter pub get

      - name: Lint App
        run: flutter analyze