name: Frontend deployment

on:
  workflow_dispatch: # This event allows you to manually trigger the workflow

defaults:
  run:
    working-directory: ./app
    shell: bash

jobs:
  Frontend-deployment:
    runs-on: ubuntu-latest

    steps:
      - name : Checkout
        uses: actions/checkout@v4.2.1
        with:
          fetch-depth: 0

      - name: Set up Java 17 Microsoft
        uses: actions/setup-java@v4.4.0
        with:
          distribution: 'microsoft'
          java-version: '17'

      - name: Set up Flutter 3.24.3
        uses: subosito/flutter-action@v2.16.0
        with:
          flutter-version: '3.24.3'
          channel: 'stable'
          cache: true

      - name: Get dependencies
        run: flutter pub get

      - name: Build realease APK
        run: flutter build apk --release

      - name: 'Get Previous tag'
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@v1.4.0"

      - name: create release
        uses: softprops/action-gh-release@v0.1.15 # 2.0.8
        with:
          files: |
            ./app/build/app/outputs/flutter-apk/app-release.apk
          tag_name: ${{ steps.previoustag.outputs.tag }}
          token: ${{ secrets.RELEASE_GA_TOKEN }}